// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjROD0oFqDfrZy7TM_Eybjuj1ZJJcP6cw',
    appId: '1:637135525658:web:0d2c25f6c43d6877f13ea3',
    messagingSenderId: '637135525658',
    projectId: 'ilham-query',
    authDomain: 'ilham-query.firebaseapp.com',
    storageBucket: 'ilham-query.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0JeXlB1EmiPKhIJxaZn-VIhFGCVssG7s',
    appId: '1:637135525658:android:1aa77ca9a18beacef13ea3',
    messagingSenderId: '637135525658',
    projectId: 'ilham-query',
    storageBucket: 'ilham-query.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe7g2Ku8Ihr0uoX70eXdDCotKFzttmG1s',
    appId: '1:637135525658:ios:de6595bc303652dcf13ea3',
    messagingSenderId: '637135525658',
    projectId: 'ilham-query',
    storageBucket: 'ilham-query.firebasestorage.app',
    iosBundleId: 'com.example.dice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe7g2Ku8Ihr0uoX70eXdDCotKFzttmG1s',
    appId: '1:637135525658:ios:de6595bc303652dcf13ea3',
    messagingSenderId: '637135525658',
    projectId: 'ilham-query',
    storageBucket: 'ilham-query.firebasestorage.app',
    iosBundleId: 'com.example.dice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjROD0oFqDfrZy7TM_Eybjuj1ZJJcP6cw',
    appId: '1:637135525658:web:6f3cf08b0309e984f13ea3',
    messagingSenderId: '637135525658',
    projectId: 'ilham-query',
    authDomain: 'ilham-query.firebaseapp.com',
    storageBucket: 'ilham-query.firebasestorage.app',
  );
}
